routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/blog/category/{id?}', 'BlogController@categoryById')->name('category');
Route::get('/blog/item/{id?}', 'BlogController@itemById')->name('item');
Route::get('/cart/', 'CartController@index')->name('cart.index');
Route::post('/cart/add_to_cart/', 'CartController@addToCart')->name('cart.add_to_cart');
Route::post('/cart/remove_cart/', 'CartController@removeCartById')->name('cart.remove_cart');
Route::post('/cart/update_item_cart/', 'CartController@updateItemInCart')->name('cart.update_item_cart');
Route::post('/validationPost','FormController@validationPost')->name('validationPost');

Route::group( ['middleware' => 'auth' ], function()
{
    Route::get('/checkout/', 'CartController@checkout')->name('checkout');
    Route::post('/order/', 'CartController@order')->name('order');
    Route::post('/rating_star/', 'CartController@ratingStar')->name('rating_star');
    Route::post('/check_promo_code/', 'CartController@checkPromoCode')->name('checkPromoCode');

});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth','admin'] ], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/order', 'OrderController', ['as'=>'admin']);
    Route::resource('/item', 'ItemController', ['as'=>'admin']);
    Route::resource('/user', 'UserController', ['as'=>'admin']);
    Route::resource('/promo', 'PromoController', ['as'=>'admin']);
    Route::resource('/promotion', 'PromotionController', ['as'=>'admin']);
    Route::resource('/category', 'CategoryController', ['as'=>'admin']);
    Route::post('/dropzoneUpload', 'ItemController@dropzoneUploadImages')->name('admin.dropzoneUpload');
    Route::post('/dropzoneDelete', 'ItemController@dropzoneDeleteImages')->name('admin.dropzoneDelete');
    Route::post('/remove_item_img/', 'ItemController@removeItemImgById')->name('admin.remove_item_img');
    Route::post('/remove_user_img/', 'UserController@removeUserImgById')->name('admin.remove_user_img');
    Route::post('/remove_item_main_img/', 'ItemController@removeItemMainImgById')->name('admin.remove_item_main_img');

});
Route::get('/', 'BlogController@index', function () {
    return view('/blog.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Promo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\SoftDeletes;

class Promo extends Model
{
    protected $fillable = ['id','title', 'promo','expiry_date','sale_percent', 'created_at', 'updated_at'];

    protected $dates = ['deleted_at'];

    public function setPromoAttribute($value) {

        $this->attributes['promo'] = Str::slug( mb_substr($this->title, 0, 5) . "-" . \Carbon\Carbon::now()->format('dHi'), '-');
    }
}

app/Http/Controllers/Admin/PromoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Promo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PromoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.promo.index',[
            'promo_cods' => Promo::where('deleted_at','0')->paginate(10),
            'date' => \Carbon\Carbon::now()->format('Ymd'),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.promo.create', [
            'promo_cod'    => [],
            'delimiter'  => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Promo::create($request->all());
        return redirect()->route('admin.promo.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Promo  $promo
     * @return \Illuminate\Http\Response
     */
    public function show(Promo $promo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Promo  $promo
     * @return \Illuminate\Http\Response
     */
    public function edit(Promo $promo)
    {
        return view('admin.promo.edit',[
            'promo'   => $promo,
            'promos' => Promo::get(),
            'delimiter'  => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Promo  $promo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Promo $promo)
    {
        $promo->update($request->all());
        return redirect()->route('admin.promo.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Promo  $promo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Promo $promo)
    {
        Promo::where('id', $promo->id)->update([
            'deleted_at' => '1',
        ]);
        return redirect()->route('admin.promo.index');
    }

}

resources/views/admin/promo/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        <hr />
        <form class="form-horizontal" action="{{route('admin.promo.store')}}" method="post">
            {{ csrf_field() }}
            <div class="col-12">
                <label for="">Title</label>
                <input  type="text" class="form-control" placeholder="Title" name="title" value="" required>
            </div>
            <hr />
            <div class="col-12">
                <label for="">Promo Code (Unique value)</label>
                <input  type="text" class="form-control" placeholder="Automatic generation" name="promo" value="" readonly="">
            </div>
            <hr />
            <div class="form-inline">
                <div class="col-6">
                    <label class="sr-only" for="datepicker">Expiry Date</label>
                    <input type="text" class="form-control" name="expiry_date" id="datepicker" placeholder="Expiry Date" required>
                </div>
                <div class="col-6">
                    <label class="sr-only" for="sale_percent">Sale Percent</label>
                    <div class="input-group">
                        <input type="number" class="form-control" id="sale_percent" name="sale_percent" placeholder="Sale Percent" value="" required>
                        <div class="input-group-prepend">
                            <div class="input-group-text">%</div>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div class="col-6">
                <input class="btn btn-primary" type="submit" value="Save">
            </div>
        </div>
    </div>
@endsection

resources/views/admin/promo/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        <hr />
        <form class="form-horizontal" action="{{route('admin.promo.update',$promo)}}" method="post">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}
            <div class="col-12">
                <label for="">Title</label>
                <input  type="text" class="form-control" placeholder="Title" name="title" value="{{$promo->title or ""}}" required>
            </div>
            <hr />
            <div class="col-12">
                <label for="">Promo Code (Unique value)</label>
                <input  type="text" class="form-control" placeholder="Automatic generation" name="promo" value="{{$promo->promo or ""}}" readonly="">
            </div>
            <hr />
            <div class="form-inline">
                <div class="col-6">
                    <label class="sr-only" for="datepicker">Expiry Date</label>
                    <input type="text" class="form-control" name="expiry_date" id="datepicker" placeholder="Expiry Date" value="{{$promo->expiry_date or ""}}" required>
                </div>
                <div class="col-6">
                    <label class="sr-only" for="sale_percent">Sale Percent</label>
                    <div class="input-group">
                        <input type="number" class="form-control" id="sale_percent" name="sale_percent" placeholder="Sale Percent" value="{{$promo->sale_percent or ""}}" required>
                        <div class="input-group-prepend">
                            <div class="input-group-text">%</div>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div class="col-6">
                <input class="btn btn-primary" type="submit" value="Update">
            </div>
    </div>
    </div>
@endsection

resources/views/admin/promo/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        <hr>
        <a href="{{route('admin.promo.create')}}" class="btn btn-primary pull-right">
            <i class="fa fa-plus-square-o"></i> Create Promo Code
        </a>
        <table class="table table-striped">
            <thead>
            <th>Title</th>
            <th>Promo Code</th>
            <th>expiry_date</th>
            <th>Sale Percent</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th class="text-right">Action</th>
            </thead>
            <tbody>
            @forelse ($promo_cods as $promo_cod)
                <tr
                   @if($date > date('Ymd', strtotime($promo_cod->expiry_date)))
                       class="alert-danger"
                           @endif>
                    <td>{{$promo_cod->title}}</td>
                    <td>{{$promo_cod->promo}}</td>
                    <td>{{$promo_cod->expiry_date}}</td>
                    <td>{{$promo_cod->sale_percent}} %</td>
                    <td>{{$promo_cod->created_at}}</td>
                    <td>{{$promo_cod->updated_at}}</td>
                    <td class="text-right">
                        <form onsubmit="if(confirm('Delete ?')){return true}else{return false}" action="{{route('admin.promo.destroy',$promo_cod)}}" method="post">
                            <input type="hidden" name="_method" value="DELETE">
                            {{ csrf_field()}}
                            <a class="btn btn-default" href="{{route('admin.promo.edit', $promo_cod)}}"><i class="fa fa-edit"></i></a>
                            <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="12" class="text-center"><h2>No data available</h2></td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <tr>
                <td colspan="12">
                    <ul class="pagination pull-right">
                        {{ $promo_cods->links() }}
                    </ul>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

@endsection