routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/blog/category/{id?}', 'BlogController@categoryById')->name('category');
Route::get('/blog/item/{id?}', 'BlogController@itemById')->name('item');
Route::get('/cart/', 'CartController@index')->name('cart.index');
Route::post('/cart/add_to_cart/', 'CartController@addToCart')->name('cart.add_to_cart');
Route::post('/cart/remove_cart/', 'CartController@removeCartById')->name('cart.remove_cart');
Route::post('/cart/update_item_cart/', 'CartController@updateItemInCart')->name('cart.update_item_cart');
Route::post('/validationPost','FormController@validationPost')->name('validationPost');

Route::group( ['middleware' => 'auth' ], function()
{
    Route::get('/checkout/', 'CartController@checkout')->name('checkout');
    Route::post('/order/', 'CartController@order')->name('order');
    Route::post('/rating_star/', 'CartController@ratingStar')->name('rating_star');
    Route::post('/check_promo_code/', 'CartController@checkPromoCode')->name('checkPromoCode');

});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth','admin'] ], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/order', 'OrderController', ['as'=>'admin']);
    Route::resource('/item', 'ItemController', ['as'=>'admin']);
    Route::resource('/user', 'UserController', ['as'=>'admin']);
    Route::resource('/promo', 'PromoController', ['as'=>'admin']);
    Route::resource('/promotion', 'PromotionController', ['as'=>'admin']);
    Route::resource('/category', 'CategoryController', ['as'=>'admin']);
    Route::post('/dropzoneUpload', 'ItemController@dropzoneUploadImages')->name('admin.dropzoneUpload');
    Route::post('/dropzoneDelete', 'ItemController@dropzoneDeleteImages')->name('admin.dropzoneDelete');
    Route::post('/remove_item_img/', 'ItemController@removeItemImgById')->name('admin.remove_item_img');
    Route::post('/remove_user_img/', 'UserController@removeUserImgById')->name('admin.remove_user_img');
    Route::post('/remove_item_main_img/', 'ItemController@removeItemMainImgById')->name('admin.remove_item_main_img');

});
Route::get('/', 'BlogController@index', function () {
    return view('/blog.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/layouts/app_admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/admin/main.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/min/dropzone.min.css">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/dropzone.js"></script>
    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/js/gijgo.min.js" type="text/javascript"></script>
    <script src="{{ asset('js/admin/main.js') }}"></script>

</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                Laravel
            </a>
            <a class="navbar-brand" href="{{ url('/admin') }}">
                Dashboard
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.category.index') }}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.item.index') }}">Items</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.user.index') }}">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.order.index') }}">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.promo.index') }}">Promo Codes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.promotion.index') }}">Promotions</a>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>