routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/blog/category/{id?}', 'BlogController@categoryById')->name('category');
Route::get('/blog/item/{id?}', 'BlogController@itemById')->name('item');
Route::get('/cart/', 'CartController@index')->name('cart.index');
Route::post('/cart/add_to_cart/', 'CartController@addToCart')->name('cart.add_to_cart');
Route::post('/cart/remove_cart/', 'CartController@removeCartById')->name('cart.remove_cart');
Route::post('/cart/update_item_cart/', 'CartController@updateItemInCart')->name('cart.update_item_cart');
Route::post('/validationPost','FormController@validationPost')->name('validationPost');

Route::group( ['middleware' => 'auth' ], function()
{
    Route::get('/checkout/', 'CartController@checkout')->name('checkout');
    Route::post('/order/', 'CartController@order')->name('order');
    Route::post('/rating_star/', 'CartController@ratingStar')->name('rating_star');
    Route::post('/check_promo_code/', 'CartController@checkPromoCode')->name('checkPromoCode');

});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth','admin'] ], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/order', 'OrderController', ['as'=>'admin']);
    Route::resource('/item', 'ItemController', ['as'=>'admin']);
    Route::resource('/user', 'UserController', ['as'=>'admin']);
    Route::resource('/promo', 'PromoController', ['as'=>'admin']);
    Route::resource('/promotion', 'PromotionController', ['as'=>'admin']);
    Route::resource('/category', 'CategoryController', ['as'=>'admin']);
    Route::post('/dropzoneUpload', 'ItemController@dropzoneUploadImages')->name('admin.dropzoneUpload');
    Route::post('/dropzoneDelete', 'ItemController@dropzoneDeleteImages')->name('admin.dropzoneDelete');
    Route::post('/remove_item_img/', 'ItemController@removeItemImgById')->name('admin.remove_item_img');
    Route::post('/remove_user_img/', 'UserController@removeUserImgById')->name('admin.remove_user_img');
    Route::post('/remove_item_main_img/', 'ItemController@removeItemMainImgById')->name('admin.remove_item_main_img');

});
Route::get('/', 'BlogController@index', function () {
    return view('/blog.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'last_name', 'email', 'role', 'image', 'password', 'address', 'address_2', 'state', 'zip','balance' ,'deleted_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    public function admin()
    {
        return $this->admin;
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public $image_name = 'default_u_image.png';

    public function index()
    {
        return view('admin.user.index', [
            'users' => User::where('deleted_at','0')->paginate(10)
        ]);
    }

    protected function validator(array $request)
    {
        return Validator::make($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create', [
            'user' => [],
            'delimiter' => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validator($request->all())->validate();
        $image_name = $this->image_name;
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $image_name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/users');
            $imagePath = $destinationPath . "/" . $image_name;
            $image->move($destinationPath, $image_name);
        }
        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'last_name' => $request->last_name,
            'role' => $request->role,
            'balance' => $request->balance,
            'image' => $image_name,
            'password' => Hash::make($request->password),
        ]);
        return redirect()->route('admin.user.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user.edit', [
            'user' => $user,
            'delimiter' => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        if ($request->image){
            $image_name = $request->image;
        }else{
            $image_name = $this->image_name;
        }
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $image_name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/users');
            $image->move($destinationPath, $image_name);
        }

        User::where('email', $request->email)->update([
            'name' => $request->name,
            'email' => $request->email,
            'last_name' => $request->last_name,
            'role' => $request->role,
            'balance' => $request->balance,
            'image' => $image_name,
            'password' => Hash::make($request->password),
        ]);

        return redirect()->route('admin.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, User $user)
    {
        User::where('id', $user->id)->update([
            'deleted_at' => '1',
        ]);
        return redirect()->route('admin.user.index');
    }

    public function removeUserImgById(Request $request)
    {
        User::where('id', $request->id)->update([
            'image' => $this->image_name,]);
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        <hr />
        <form class="form-horizontal" enctype="multipart/form-data" action="{{route('admin.user.store')}}" method="post">
            {{ csrf_field() }}
            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                <div class="col-md-6">
                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Name"  name="name" value="{{ old('name') }}" required autofocus>
                    @if ($errors->has('name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name</label>
                <div class="col-md-6">
                    <input type="text" id="last_name" class="form-control" name="last_name" placeholder="Last Name" value="{{ old('last_name') }}" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
                <div class="col-md-6">
                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="Email" name="email" value="{{ old('email') }}" required>
                    @if ($errors->has('email'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label for="role" class="col-md-4 col-form-label text-md-right">Role</label>
                <div class="col-md-6">
                    <select class="form-control" id="role" name="role">
                        <option value="user" selected="selected">User</option>
                        <option value="editor">Editor</option>
                        <option value="admin">Admin</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="balance" class="col-md-4 col-form-label text-md-right">{{ __('Balance') }}</label>
                <div class="col-md-6">
                    <input id="balance" type="number" min="0" class="form-control" placeholder="Balance" name="balance" value="">
                </div>
            </div>
            <div class="form-group row">
                <label for="image" class="col-md-4 col-form-label text-md-right">Image</label>
                <div class="col-md-6" >
                    <input type="file" name="image" id="image" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>
                <div class="col-md-6">
                    <input id="password" type="password" placeholder="Password"  class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>
                    @if ($errors->has('password'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>
                <div class="col-md-6">
                    <input id="password-confirm" type="password" placeholder="Confirm Password"  class="form-control" name="password_confirmation" required>
                </div>
            </div>
            <hr />
            <div class="form-group row">
                <div class="col-md-12 text-md-center">
                    <input class="btn btn-primary" type="submit" value="Save">
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        <hr />
        <form class="form-horizontal" enctype="multipart/form-data" action="{{route('admin.user.update',$user)}}" method="post">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}
            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                <div class="col-md-6">
                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Name"  name="name" value="{{ $user->name }}" required autofocus>
                    @if ($errors->has('name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name</label>
                <div class="col-md-6">
                    <input type="text" id="last_name" class="form-control" name="last_name" placeholder="Last Name" value="{{ $user->last_name }}" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
                <div class="col-md-6">
                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="Email" name="email" value="{{ $user->email }}" required>
                    @if ($errors->has('email'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label for="role" class="col-md-4 col-form-label text-md-right">Role</label>
                <div class="col-md-6">
                    <select class="form-control" id="role" name="role">
                        <option value="user"  @if ($user->role == 'user') selected="selected" @endif>User</option>
                        <option value="editor" @if ($user->role == 'editor') selected="selected" @endif>Editor</option>
                        <option value="admin" @if ($user->role == 'admin') selected="selected" @endif>Admin</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="balance" class="col-md-4 col-form-label text-md-right">{{ __('Balance') }}</label>
                <div class="col-md-6">
                    <input id="balance" type="number" min="0" class="form-control" placeholder="Balance" name="balance" value="{{ $user->balance or ""}}" required>
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="image" class="col-md-4 col-form-label text-md-right">Image</label>
                <div class="col-2 upload_img u_img{{$user->id}}">
                    <span class="remove_user_img_btn" data-id="{{$user->id}}"><i class="fa fa-remove"></i></span>
                    <img  src="/uploads/users/{{$user->image or ""}}" style="width: 100px; height: 100px;" />
                    <input type="hidden" name="image" value="{{$user->image or ""}}" class="form-control">
                </div>
                <div class="col-md-4" >
                    <input type="file" name="image" id="image" value="{{$user->image or ""}}" class="form-control">
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>
                <div class="col-md-6">
                    <input id="password" type="password" placeholder="Password"  class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>
                    @if ($errors->has('password'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>
                <div class="col-md-6">
                    <input id="password-confirm" type="password" placeholder="Confirm Password"  class="form-control" name="password_confirmation" required>
                </div>
            </div>
            <hr />
            <div class="form-group row">
                <div class="col-md-12 text-md-center">
                    <input class="btn btn-primary" type="submit" value="Update">
                </div>
            </div>
        </form>
    </div>
    <script type="text/javascript">
        $("body").on("click", ".remove_user_img_btn", function () {
            var id = $(this).data('id');
            $.ajax(
                {
                    url: "{{route('admin.remove_user_img')}}",
                    type: "POST",
                    datatype: "text",
                    data: {id: id},
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                })
            $('.u_img' + id).remove();
        });
    </script>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        <hr>
        <a href="{{route('admin.user.create')}}" class="btn btn-primary pull-right">
            <i class="fa fa-plus-square-o"></i> Create User
        </a>
        <table class="table table-striped">
            <thead>
            <th>Name</th>
            <th>last Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Balance</th>
            <th>Image</th>
            <th class="text-right">Action</th>
            </thead>
            <tbody>
            @forelse ($users as $user)
                <tr>
                    <td>{{$user->name}}</td>
                    <td>{{$user->last_name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->role}}</td>
                    <td>{{$user->balance}} $</td>
                    <td><img  src="/uploads/users/{{$user->image or ""}}" style="width: 100px; height: 100px;" /></td>
                    <td class="text-right">
                        <form onsubmit="if(confirm('Delete ?')){return true}else{return false}" action="{{route('admin.user.destroy',$user)}}" method="post">
                            <input type="hidden" name="_method" value="DELETE">
                            {{ csrf_field()}}
                            <a class="btn btn-default" href="{{route('admin.user.edit', $user)}}"><i class="fa fa-edit"></i></a>
                            <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="12" class="text-center"><h2>No data available</h2></td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <tr>
                <td colspan="12">
                    <ul class="pagination pull-right">
                        {{ $users->links() }}
                    </ul>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

@endsection